# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hexxing Hunt
email:
description: >- # this means to ignore newlines until "baseurl:"
  Made by Studio GJTW
baseurl: /
url: https://deckardkane.github.io/Hexxing-Hunt
short_bio: (change or remove this)
twitter_username: # we don't have a twitter
github_username: DeckardKane
minimal_mistakes_skin: witch # consider contrast and air as well?
search: true

#show_downloads: true
#github:
#  zip_url: https://github.com/DeckardKane/Hexxing-Hunt/releases
#  tar_url: https://github.com/DeckardKane/Hexxing-Hunt/releases

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts
  - _collections

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .vs/* # here are my additions to the exclude list
   - Builds/*
   - Library/*
   - Logs/*
   - obj/*
   - Assembly-CSharp-Editor.csproj
   - Assembly-CSharp.csproj
   - Hexxing Hunt.csproj
   - Hexxing Hunt.Editor.csproj
   - Hexxing Hunt.sln
   - Two-Player Splitscreen Starter.sln
   - Unity.Analytics.DataPrivacy.csproj
   - Unity.CollabProxy.Editor.csproj
   - Unity.Rider.Editor.csproj
   - Unity.TextMeshPro.csproj
   - Unity.TextMeshPro.Editor.csproj
   - Unity.VSCode.Editor.csproj
   - UnityEditor.TestRunner.csproj
   - UnityEngine.TestRunner.csproj


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Peter Turnbull"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Artist and mad scientist from California, studying and working in Baltimore."
  links:
    # - label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://"
    - label: "ArtStation"
      icon: "fab fa-fw fa-artstation"
      url: "https://www.artstation.com/deckardkane"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DeckardKane"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pcturnbull7"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/pcturnbull/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DeckardKane/Hexxing-Hunt/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
